[[edge_functions]]
  path = "/test"
  function = "hello"
[[edge_functions]]
  path = "/*"
  function = "index"
[[redirects]]
  from = "/proxy/*"
  to = "https://i-video.vercel.app/api/proxy"
  status = 200
